### ISSUE TITLE
Different solidity versions have been used in different contracts

### ISSUE THREAD

**Issue by ryu9827** [tikonoff/staking-app#1]
0.4.18
https://github.com/tikonoff/staking-app/blob/8306bb8deebe0f554e99bf4e525ea4a3f5672397/contracts/Stake.sol#L11

0.4.11
https://github.com/tikonoff/staking-app/blob/8306bb8deebe0f554e99bf4e525ea4a3f5672397/contracts/SafeMath.sol#L1

consistent version should be used in all contracts.

**Comment by ryu9827** [comment]
If they don't accept [issue 8](https://github.com/tikonoff/staking-app/issues/8) this is not an issue.

**Comment by Janther** [comment]
this is not an issue if you consider #8 and if you don't, is just a minor issue.
